# generated by datamodel-codegen:
#   filename:  service.json
#   timestamp: 2022-11-30T10:44:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Role(Enum):
    producer = 'producer'
    licensor = 'licensor'
    processor = 'processor'
    host = 'host'


class Provider(BaseModel):
    name: str = Field(..., title='Organization name')
    description: Optional[str] = Field(None, title='Organization description')
    roles: Optional[List[Role]] = Field(None, title='Organization roles')
    url: Optional[str] = Field(None, title='Organization homepage')


class Type(Enum):
    STAC = 'STAC'
    WFS = 'WFS'
    WMS = 'WMS'
    WMTS = 'WMTS'
    XYZ = 'XYZ'


class Model(BaseModel):
    title: str
    description: str
    providers: List[Provider]
    type: Type
    url: str
    ping_url: Optional[str] = None
    ssys_targets: Optional[List[str]] = Field(None, alias='ssys:targets')
