# generated by datamodel-codegen:
#   filename:  https://stac-extensions.github.io/projection/v1.0.0/schema.json
#   timestamp: 2022-12-07T18:54:27+00:00

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, Field

from . import (
    ConcatenatedOperation,
    Crs,
    Datum,
    DatumEnsemble,
    Ellipsoid,
    PrimeMeridian,
    SingleOperation,
)


class Schema(BaseModel):
    __root__: Union[
        Crs,
        Datum,
        DatumEnsemble,
        Ellipsoid,
        PrimeMeridian,
        SingleOperation,
        ConcatenatedOperation,
    ] = Field(..., description='Schema for PROJJSON (v0.2.1)')


Schema.update_forward_refs()
